//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmProjem.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filmler
    {
        public int ID { get; set; }
        public string FilmAdi { get; set; }
        public string FilmYonetmeni { get; set; }
        public Nullable<double> IMDBPuani { get; set; }
        public Nullable<int> FilmTuruID { get; set; }
        public Nullable<System.TimeSpan> FilmSuresi { get; set; }
        public Nullable<System.DateTime> FilmYili { get; set; }
    }
}
