//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmProjem.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanıcılar
    {
        public int ID { get; set; }
        public string AdiSoyadi { get; set; }
        public string Eposta { get; set; }
        public string Şifre { get; set; }
        public Nullable<bool> AktifPasif { get; set; }
    }
}
